# Generated by Django 4.2.1 on 2023-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='is_successful',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='health_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
