# Generated by Django 4.2.1 on 2023-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_remove_sensordata_is_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='is_successful',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
