version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5432:${DATABASE_PORT}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  sensor-mock:
    build:
      context: ./sensor-mock
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./sensor-mock:/app
    ports:
      - 5000:5000

  web-app:
    build:
      context: ./interviewProject
    command: gunicorn --bind 0.0.0.0:8000 interviewProject.wsgi
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOST=${DJANGO_ALLOWED_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=timescaledb
      - REDIS_HOST=redis
      - SENSOR_HOST=sensor-mock

    volumes:
      - ./interviewProject:/app
    ports:
      - 8000:8000
    depends_on:
      - timescaledb
      - sensor-mock
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    build: ./interviewProject
    command: celery -A interviewProject worker -l info
    volumes:
      - ./interviewProject:/app/
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOST=${DJANGO_ALLOWED_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=timescaledb
      - REDIS_HOST=redis
      - SENSOR_HOST=sensor-mock
    depends_on:
      - redis
      - sensor-mock

  celery-beat:
    build: ./interviewProject
    command: celery -A interviewProject beat -l info
    volumes:
      - ./interviewProject:/app/
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOST=${DJANGO_ALLOWED_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=timescaledb
      - REDIS_HOST=redis
      - SENSOR_HOST=sensor-mock
    depends_on:
      - redis
      - sensor-mock

volumes:
  pgdata:
